version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  myapp:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres # Updated database name to "postgres"
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8080:8080"
    command: ["java", "-jar", "your-app.jar"]

  liquibase:
    image: liquibase/liquibase:latest
    depends_on:
      - db
    command: ["--url=jdbc:postgresql://db:5432/postgres", "--changeLogFile=changelog-master.xml", "update"] # Updated database name to "postgres"
    volumes:
      - ./liquibase:/liquibase/changelog
    environment:
      - LIQUIBASE_USERNAME=postgres
      - LIQUIBASE_PASSWORD=postgres

volumes:
  postgres-data:
